variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - echo '---' >tests/test.yml
  - "echo '- hosts: localhost' >>tests/test.yml"
  - "echo '  remote_user: root' >>tests/test.yml"
  - "echo '  roles:' >>tests/test.yml"
  - "echo '    - '\"$(basename \"$CI_PROJECT_DIR\")\"'' >>tests/test.yml"

stages:
  - test

test:
  stage: test
  image: python:2.7
  script:
    - mkdir -p tests/roles/ && git clone "$(echo $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;")/ZerBytes/ansible/roles/common-facts.git" tests/roles/zerbytes.common-facts/
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
