---
- include: repo-deb.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- include: repo-rhel.yml
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu" and not is_coreos

- name: Install/Update docker-engine package
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: docker-engine
    state: latest

- include: coreos.yml
  when: is_coreos

- name: Create Docker socket service
  template:
    src: "docker.socket.j2"
    dest: "{{ systemd_unit_path }}/docker.socket"
  notify:
  - reload systemd
  - restart docker

- name: Create Docker service
  template:
    src: "docker.service.j2"
    dest: "{{ systemd_unit_path }}/docker.service"
  notify:
  - reload systemd
  - restart docker
