---
- name: Set docker config file directory
  set_fact:
    docker_config_dir: "/etc/sysconfig"

- name: Override docker config file directory for Debian
  set_fact:
    docker_config_dir: "/etc/default"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- include: debian-install.yml
  when: ansible_distribution == "Debian"

- include: apt-docker-install.yml
  when: ansible_distribution == "Ubuntu"

- include: generic-install.yml
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- include: docker-comfiguration.yml

- include: cleanup-cronjob.yml
