---
- name: Override docker config file directory for Debian
  set_fact:
    docker_config_dir: "/etc/default"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Create config file directory
  file:
    path: "{{ docker_config_dir }}"
    state: directory

- include: install.yml

- include: configuration.yml

- include: cronjob-cleanup.yml
